#!/usr/bin/env perl

use lib qw(lib /home/webmaster/git/perl/Net-OAuth-All/lib);
use Mojolicious::Lite;
use Data::Dumper;

get '/'                => 'index';
get '/oauth_error'     => 'oauth_error';

get '/login/:provider' => sub {
	my $self = shift;
	
	return $self->redirect_to('/oauth_error/') unless $self->helper('oauth_login' => $self->stash('provider'));
	return;
};
get '/oauth/:provider' => sub {
	my $self = shift;
	
	return $self->redirect_to('/oauth_error/') unless $self->helper('oauth_callback');
	
	my $oauth = $self->session('oauth');
	my $res = $self->helper('oauth_request'
		=> $oauth->{'oauth_provider'}
		=> {
			map {$_ => $oauth->{$_}} qw/access_token access_token_secret/
		}
	);
	
	$self->render(
		'data' => Dumper($res ? $res->json : {})
	);
} => 'oauth';

for (ref(app)) {
	$_->attr('conf' => sub { do 'script/app.conf' });
	
	$ENV{'OAUTH_DEBUG'} = 1;
	plugin 'o_auth', $_->conf;
	
	$_->start;
}

__DATA__

@@ index.html.ep
% layout 'funky';
	<% for (keys %{$self->app->conf}) { %>
		<a href="/login/<%= $_ %>/"><%= $_ %></a><br/>
	<% } %>

@@ oauth.html.ep
% layout 'funky';
	<%= $data %>
	
@@ oauth_error.html.ep
% layout 'funky';
Can`t login

@@ layouts/funky.html.ep
<!doctype html><html>
    <head><title>OAuth TEST!</title></head>
    <body><%== content %></body>
</html>
